version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=gifiti_production
      - DB_USER=gifiti_user
      - DB_PASSWORD=gifiti_password
      - JWT_SECRET=tu_jwt_secret_muy_seguro
      - CORS_ORIGIN=https://tu-dominio.com
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=gifiti_production
      - POSTGRES_USER=gifiti_user
      - POSTGRES_PASSWORD=gifiti_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
